version: '3.8'

services:
  postgres:
    image: "postgres:17-alpine"
    platform: linux/amd64
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/backend-api
    networks:
      - backend

volumes:
  postgres:

networks:
  backend:
    driver: "bridge"
